---
title: "Lab 03 - Nobel laureates"
author: "Cailey Fay"
date: "10.7.25"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r summarize}
nrow(nobel)
ncol(nobel)
#There are 26 variables and 935 observations. 
```

Remove this text, and add your answer for Exercise 1 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.

### Exercise 2

```{r data frames}
nobel_living <-nobel %>%
      filter(is.na(died_date),gender != "org", !is.na(country))

nobel_living %>%
  select(died_date, gender, country)

nobel_living_frame <-as.data.frame(nobel_living %>%
  select(died_date, gender, country))

nrow(nobel_living_frame)

```


### Exercise 3

```{r mutate}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )

nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
#nobel_living_science has everything in terms of US or not at the time of winning the prize, and narrows down the disciplines to physics, medicine, chemistry, and econ 

#faceted bar plot 
ggplot(nobel_living_science, aes(x = country_us)) +
  geom_bar() +
  coord_flip() +
  facet_wrap(~ category) +
  labs(title = "Bar Plot Faceted by Prize Category", 
       x = "Country", 
       y = "Number of Prizes Won")

```

### Exercise 4: 105 from the US, and 123 from other countries 
```{r}
nobel_living <-nobel_living %>%
  mutate(
   born_country_us = if_else(born_country == "USA", "USA", "Other")
  )

table(nobel_living$born_country_us)
```
...

### Exercise 5

...

### Exercise 6

...
